### ISSUE TITLE
No session_start in component is causing php_captcha class to read an empty $_SESSION array.

### ISSUE THREAD

**Issue by extrablind** [hashmode/cakephp-captcha#2]
When no call to session is made prior construct new PhpCaptcha() no session exists because no session_start() function have been called.

**Comment by hashmode** [comment]
I am using the plugin currently in a few projects and there was no issues, could you please describe the error your are having ?

**Comment by extrablind** [comment]
The function check from captcha component always returns false. From my point of view this is because no session has been started by cakephp when the PhpCaptcha class is called. 
The function session_start seems to be called on first access of cakephp session class (not verified).
Then it could not retrieve the session $_SESSION['php_captcha']. To "force" cakephp to start the session. Reading the session can be a solution (see PR). 

To reproduce the issue : 
install a new cakephp project
composer install the component, 
call the component in a page, 
be sure NOT having started manually the session or called the session component prior to the captcha component

> The captcha will appear but the check will always be false as $_SESSION is empty because PhpCatcha can not populate it.

Maybe there is a better solution to force starting the session, I can figure it out and make another PR if needed. 

Regards

**Comment by hashmode** [comment]
Thanks for the PR, I merged it. I always used it with Auth component and as it internally started the session I never had this issue.

**Comment by extrablind** [comment]
My pleasure ! By the way thanks for this plugin.
